import { CreatineReportProps } from "@/components/templates/CreatineReportTemplate";
import type { UploadedTemplate } from "@/lib/templates/uploadedTypes";
import { buildCreatineReportHtml } from "./buildStaticHtml";
import { buildUploadedTemplateFiles } from "./buildUploadedTemplateFiles";

export type StaticFile = {
  path: string;
  contents: string;
};

function escapeHtml(text: string): string {
  const map: { [key: string]: string } = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;',
  };
  return text.replace(/[&<>"']/g, (m) => map[m]);
}

/**
 * Build WordPress template files for CreatineReport template
 */
export function buildWordPressTemplate(props: CreatineReportProps, slug: string): StaticFile[] {
  const htmlContent = buildCreatineReportHtml(props);
  
  // Extract CSS from the HTML (it should be in a <style> tag or linked)
  // For now, we'll create a separate CSS file
  const cssMatch = htmlContent.match(/<style[^>]*>([\s\S]*?)<\/style>/i);
  const cssContent = cssMatch ? cssMatch[1] : '';

  // Create WordPress PHP template
  const phpTemplate = `<?php
/**
 * Template Name: ${props.pageTitle}
 * Template Post Type: page
 * 
 * Generated by Site Generator
 * Slug: ${slug}
 * Product: ${props.productName}
 */

get_header();
?>

<style>
${cssContent}
</style>

<?php
// Get custom fields or use defaults
$product_name = get_post_meta(get_the_ID(), 'product_name', true) ?: '${escapeHtml(props.productName)}';
$product_url = get_post_meta(get_the_ID(), 'product_url', true) ?: '${escapeHtml(props.productUrl)}';
$main_lead = get_post_meta(get_the_ID(), 'main_lead', true) ?: '${escapeHtml(props.mainLead)}';
$overall_rating = get_post_meta(get_the_ID(), 'overall_rating', true) ?: '${props.ratings.overallRating}';
?>

<div class="creatine-funnel-container">
  ${htmlContent.replace(/<!DOCTYPE html>[\s\S]*?<body[^>]*>/i, '').replace(/<\/body>[\s\S]*?<\/html>/i, '')}
</div>

<?php
get_footer();
?>`;

  // Create functions.php snippet for custom fields
  const functionsSnippet = `<?php
/**
 * Add custom meta boxes for funnel page
 */
function add_funnel_meta_boxes() {
  add_meta_box(
    'funnel_product_data',
    'Product Data',
    'render_funnel_product_meta_box',
    'page',
    'normal',
    'high'
  );
}
add_action('add_meta_boxes', 'add_funnel_meta_boxes');

function render_funnel_product_meta_box($post) {
  wp_nonce_field('save_funnel_product_data', 'funnel_product_data_nonce');
  
  $product_name = get_post_meta($post->ID, 'product_name', true);
  $product_url = get_post_meta($post->ID, 'product_url', true);
  $main_lead = get_post_meta($post->ID, 'main_lead', true);
  $overall_rating = get_post_meta($post->ID, 'overall_rating', true);
  ?>
  <table class="form-table">
    <tr>
      <th><label for="product_name">Product Name</label></th>
      <td><input type="text" id="product_name" name="product_name" value="<?php echo esc_attr($product_name); ?>" class="regular-text" /></td>
    </tr>
    <tr>
      <th><label for="product_url">Product URL</label></th>
      <td><input type="url" id="product_url" name="product_url" value="<?php echo esc_url($product_url); ?>" class="regular-text" /></td>
    </tr>
    <tr>
      <th><label for="main_lead">Main Lead Text</label></th>
      <td><textarea id="main_lead" name="main_lead" rows="3" class="large-text"><?php echo esc_textarea($main_lead); ?></textarea></td>
    </tr>
    <tr>
      <th><label for="overall_rating">Overall Rating</label></th>
      <td><input type="number" id="overall_rating" name="overall_rating" value="<?php echo esc_attr($overall_rating); ?>" step="0.1" min="0" max="5" /></td>
    </tr>
  </table>
  <?php
}

function save_funnel_product_data($post_id) {
  if (!isset($_POST['funnel_product_data_nonce']) || !wp_verify_nonce($_POST['funnel_product_data_nonce'], 'save_funnel_product_data')) {
    return;
  }
  
  if (defined('DOING_AUTOSAVE') && DOING_AUTOSAVE) {
    return;
  }
  
  if (!current_user_can('edit_post', $post_id)) {
    return;
  }
  
  if (isset($_POST['product_name'])) {
    update_post_meta($post_id, 'product_name', sanitize_text_field($_POST['product_name']));
  }
  if (isset($_POST['product_url'])) {
    update_post_meta($post_id, 'product_url', esc_url_raw($_POST['product_url']));
  }
  if (isset($_POST['main_lead'])) {
    update_post_meta($post_id, 'main_lead', sanitize_textarea_field($_POST['main_lead']));
  }
  if (isset($_POST['overall_rating'])) {
    update_post_meta($post_id, 'overall_rating', floatval($_POST['overall_rating']));
  }
}
add_action('save_post', 'save_funnel_product_data');
`;

  // Create README with installation instructions
  const readme = `# WordPress Export - ${slug}

## Installation Instructions

1. **Upload Template File**
   - Copy \`page-${slug}.php\` to your WordPress theme directory: \`wp-content/themes/your-theme/\`
   - Or create a child theme and place it there

2. **Add Functions Code**
   - Add the code from \`functions-snippet.php\` to your theme's \`functions.php\` file
   - This adds custom meta boxes for editing product data

3. **Create New Page**
   - In WordPress admin, go to Pages → Add New
   - Set the page template to "${props.pageTitle}"
   - Fill in the custom fields (Product Name, Product URL, etc.)
   - Publish the page

4. **Customization**
   - Edit the template file to match your theme's structure
   - Adjust CSS in the <style> tag or move to your theme's stylesheet
   - Customize the PHP variables as needed

## Files Included

- \`page-${slug}.php\` - WordPress page template
- \`functions-snippet.php\` - Code to add to functions.php
- \`README.md\` - This file

## Notes

- Make sure your theme supports custom page templates
- Test on a staging site first
- Backup your site before making changes
`;

  return [
    { path: `page-${slug}.php`, contents: phpTemplate },
    { path: 'functions-snippet.php', contents: functionsSnippet },
    { path: 'README.md', contents: readme },
  ];
}

/**
 * Build WordPress export for uploaded templates
 */
export function buildWordPressUploadedTemplate(
  template: UploadedTemplate,
  slotData: Record<string, string>,
  slug: string
): StaticFile[] {
  const files = buildUploadedTemplateFiles(template, slotData);
  const htmlFile = files.find(f => f.path === 'index.html');
  
  if (!htmlFile) {
    throw new Error('Could not generate HTML for uploaded template');
  }

  // Extract body content
  const bodyMatch = htmlFile.contents.match(/<body[^>]*>([\s\S]*?)<\/body>/i);
  const bodyContent = bodyMatch ? bodyMatch[1] : htmlFile.contents;

  // Extract CSS
  const cssFile = files.find(f => f.path === 'styles.css');
  const cssContent = cssFile ? cssFile.contents : '';

  const phpTemplate = `<?php
/**
 * Template Name: ${template.name || 'Custom Funnel'}
 * Template Post Type: page
 * 
 * Generated by Site Generator
 * Slug: ${slug}
 * Template ID: ${template.id}
 */

get_header();
?>

<style>
${cssContent}
</style>

<div class="custom-funnel-container">
  ${bodyContent}
</div>

<?php
get_footer();
?>`;

  const readme = `# WordPress Export - ${slug}

## Installation

1. Copy \`page-${slug}.php\` to your WordPress theme directory
2. Create a new page in WordPress and select this template
3. Customize as needed

## Template Info

- Template Name: ${template.name || 'Custom Template'}
- Template ID: ${template.id}
`;

  return [
    { path: `page-${slug}.php`, contents: phpTemplate },
    { path: 'README.md', contents: readme },
  ];
}

